[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_src_filter =
    +<firmware/**/*.cpp>
    +<main.cpp>
build_flags =
    -Isrc/firmware
    -Isrc/firmware/stateMachine
    -Isrc/firmware/abstractSensors
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6

