[platformio]
src_dir = src/firmware

[env:dht11]
platform = atmelavr
board = uno
framework = arduino
build_src_filter =
    +<sketches/dht11/main.cpp>
    +<sketches/dht11/DHT11Sketch.cpp>
    +<core/**/*.cpp>
    +<abstractSensors/*.cpp>
    -<core/communication/MQTTCommunication.cpp>
    -<core/communication/WiFiCommunication.cpp>
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    bblanchon/ArduinoJson @ ^7.2.0
monitor_speed = 115200